version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: cinephalia_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: cinephalia_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:15
    container_name: cinephalia_db
    environment:
      POSTGRES_DB: cinephalia
      POSTGRES_USER: cinephaliadoctrine
      POSTGRES_PASSWORD: ggy9nwhNrsLUt6N
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/db/init_data.sql:/docker-entrypoint-initdb.d/init_data.sql:ro

volumes:
  postgres_data: